Repository TransparentHealth/vmi, pull requests merged in 2020-04, with the labels that each got.

#273 Custom homepage
  apps/accounts/staff_views.py
  apps/accounts/urls.py
  apps/home/templates/authenticated-home.html
  apps/home/templates/organization-user-dashboard.html
  apps/home/urls.py
  apps/home/views.py
  templates/include/main-nav.html
  vmi/settings.py
  vmi/urls.py
Labels: enhancement

#279 Fix index template
  apps/accounts/staff_forms.py
  apps/home/templates/index.html
  apps/home/templates/smh-index.html
  apps/home/views.py
  requirements.txt
  vmi/settings.py
Labels: bug

#280 Ial ux updates
  apps/accounts/change_account_views.py
  apps/accounts/staff_forms.py
  apps/accounts/templates/login.html
  apps/home/templates/index.html
  apps/home/templates/organization-user-dashboard.html
  apps/home/templates/profile.html
  apps/home/views.py
  apps/ial/forms.py
  apps/ial/models.py
  apps/ial/views.py
  sitestatic/favicon.ico
  sitestatic/img/favicon.png
  sitestatic/img/favicon/android-chrome-192x192.png
  sitestatic/img/favicon/apple-touch-icon.png
  sitestatic/img/favicon/browserconfig.xml
  sitestatic/img/favicon/favicon-16x16.png
  sitestatic/img/favicon/favicon-32x32.png
  sitestatic/img/favicon/favicon.ico
  sitestatic/img/favicon/mstile-150x150.png
  sitestatic/img/favicon/safari-pinned-tab.svg
  sitestatic/img/favicon/site.webmanifest
  sitestatic/img/layout/logo.png
  sitestatic/img/layout/smh_app/partner_logo.png
  sitestatic/img/logo.png
  sitestatic/img/logo.svg
  static-assets/css/vmi.css
  static-assets/favicon.ico
  static-assets/img/favicon/android-chrome-192x192.png
  static-assets/img/favicon/apple-touch-icon.png
  static-assets/img/favicon/browserconfig.xml
  static-assets/img/favicon/favicon-16x16.png
  static-assets/img/favicon/favicon-32x32.png
  static-assets/img/favicon/favicon.ico
  static-assets/img/favicon/mstile-150x150.png
  static-assets/img/favicon/safari-pinned-tab.svg
  static-assets/img/favicon/site.webmanifest
  static-assets/img/layout/logo.png
  static-assets/img/logo.png
  static-assets/img/logo.svg
  templates/include/head.html
  templates/include/main-nav.html
  vmi/settings.py
Labels: enhancement

#290 Add introspection endpoint to discovery
  apps/oidc/views.py
Labels: enhancement

#295 Security update 2020 04 30 1
  templates/include/foot.html
Labels: dependencies
